#!/bin/bash -x

echo "Enter a Number"
read no
check=1

if (( $no > 1 ))
 then
	for((i=2;i<$no;i++))
   do
		if (( $no%$i == 0 ))
      then
         echo "Not a prime number"
         check=0
			break;
      fi
   done
 if (( $check == 1 ))
 then
   echo "prime Number"
 fi
else
  echo "Not a prime number"
fi

